# Generated by Django 5.1 on 2026-02-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_address_order_city_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='free_case_count',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_free',
        ),
    ]
