# Generated by Django 5.1 on 2026-03-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_remove_order_free_case_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Скидка",
            ),
        ),
    ]
