# Generated by Django 5.1 on 2026-02-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_entered_k4_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_model',
        ),
        migrations.RemoveField(
            model_name='user',
            name='free_cases',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quantity_of_cases',
        ),
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
