# Generated by Django 5.1 on 2026-02-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_case',
        ),
    ]
